name: Deploy Elastic beanstalk
on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWSACCESSKEYID }}
        aws_secret_key: ${{ secrets.AWSSECRETKEY }}
        application_name: DevOpsGettingStarted
        environment_name: Devopsgettingstarted-env
        version_label: 1
        region: us-east-2
        deployment_package: deploy.zip
